# Generated by Django 3.2.4 on 2021-11-05 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablebase',
            options={'verbose_name': 'Ученики', 'verbose_name_plural': 'Ученики'},
        ),
    ]
